[package]
name = "grind_trees_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
core = { path = "../core" }  # Local dependency on your logic
rfd = "0.15.3"               # Optional: file dialogs
lazy_static = "1.5.0"
serde_json = "1.0.140"

